USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'ELT pipeline compute warehouse';

CREATE DATABASE IF NOT EXISTS ECOMMERCE_DB
    COMMENT = 'E-commerce ELT pipeline database';

CREATE ROLE IF NOT EXISTS PIPELINE_ROLE
    COMMENT = 'Role for Airflow + dbt pipeline operations';

GRANT USAGE ON WAREHOUSE ECOMMERCE_WH  TO ROLE PIPELINE_ROLE;
GRANT USAGE ON DATABASE  ECOMMERCE_DB TO ROLE PIPELINE_ROLE;
GRANT ALL   ON DATABASE  ECOMMERCE_DB TO ROLE PIPELINE_ROLE;
GRANT CREATE SCHEMA ON DATABASE ECOMMERCE_DB TO ROLE PIPELINE_ROLE;
GRANT ROLE PIPELINE_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE WAREHOUSE ECOMMERCE_WH;
USE DATABASE ECOMMERCE_DB;